services:
  db:
    container_name: "db"
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - var/.env.dev
    ports:
      - "127.0.0.1:40001:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready'" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  pg_data:

